const db = require('./database/index.js');
const AdmZip = require('adm-zip');
const row = db.prepare('SELECT zip_content FROM artifact_versions WHERE artifact_id = ? ORDER BY saved_at DESC LIMIT 1').get('dateanddatatypes');
const zip = new AdmZip(row.zip_content);
const iflw = zip.getEntries().find(e => e.entryName.endsWith('.iflw'));
const content = zip.readAsText(iflw);
const lines = content.split('\n');
const line137 = lines[137];
console.log('RAW line 137:', JSON.stringify(line137));
const start = line137.indexOf('<value>') + 7;
console.log('Substring:', JSON.stringify(line137.substring(start, start + 30)));
const c1 = '>"Today\'s date is :- ${property.ate}"<';
console.log('c1:', content.split(c1).length - 1);
const c2 = '>"Today&apos;s date is :- ${property.ate}"<';
console.log('c2:', content.split(c2).length - 1);
const c3 = '>&quot;Today\'s date is :- ${property.ate}&quot;<';
console.log('c3:', content.split(c3).length - 1);
const c4 = '>&#34;Today\'s date is :- ${property.ate}&#34;<';
console.log('c4:', content.split(c4).length - 1);
